import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/container/layout/MainLayout";
import BottomNavBar from "@/container/layout/BottomNavBar";
import "primeicons/primeicons.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  return (
    <html>
      <body>
        <MainLayout>
          {children}
          <BottomNavBar />
        </MainLayout>
      </body>
    </html>
  );
}
